export const USERS_COLLECTION = 'users'
export const TRANSACTIONS_COLLECTION = 'transactions'
export const MONTHLY_EXPENSES_COLLECTION = 'monthlyExpenses'
export const PRIORITY_COLLECTION = 'priorityList'
export const CREDIT_CARDS_COLLECTION = 'creditCards'
