import { Metadata } from 'next'
import FooterForm from '@modules/Form/FooterForm'
import HeaderForm from '@modules/Form/HeaderForm'
import AuthContainer from '@modules/AuthContainer'
import RecoveryForm from '@modules/Form/RecoveryForm'

export const metadata: Metadata = {
  title: 'TreeX | Recuperação',
  description: 'Generated by create next app',
}

export default function Recovery() {
  return (
    <AuthContainer>
      <HeaderForm
        title="Recupere sua senha"
        description="Mantenha sua conta segura"
      />
      <RecoveryForm />
      <FooterForm
        href="/login"
        linkTitle=" Fazer login"
        label="  Já tem uma conta?"
      />
    </AuthContainer>
  )
}
