import 'swiper/css'
import './globals.css'
import dynamic from 'next/dynamic'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TreeX',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const NextThemeProvider = dynamic(
    () => import('@modules/Providers/ThemeProvider'),
    { ssr: false },
  )
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Toaster />
        <NextThemeProvider>{children}</NextThemeProvider>
      </body>
    </html>
  )
}
