import { Metadata } from 'next'
import LoginForm from '@modules/Form/LoginForm'
import FooterForm from '@modules/Form/FooterForm'
import HeaderForm from '@modules/Form/HeaderForm'
import AuthContainer from '@modules/AuthContainer'
import GoogleButton from '@elements/GoogleButton'

export const metadata: Metadata = {
  title: 'TreeX | Login',
  description: 'Generated by create next app',
}

export default function Login() {
  return (
    <AuthContainer>
      <HeaderForm
        title="Começe agora"
        description="Tenha mais controle sobre seu dinheiro"
      />
      <GoogleButton />
      <LoginForm />
      <FooterForm
        href="/register"
        linkTitle="Cadastrar"
        label="Ainda não tem uma conta?"
      />
    </AuthContainer>
  )
}
