import {
  ShoppingBag,
  Book,
  Pill,
  Utensils,
  Fuel,
  Car,
  CreditCard,
  Gamepad2,
  HeartPulse,
  ShowerHead,
  Shirt,
  Home,
  PawPrint,
  // Store,
  FileText,
  Plane,
  FileSliders,
  ShoppingCart,
} from 'lucide-react'

export const categoriesExpenses = [
  { name: 'Despesas Diversas', icon: ShoppingBag },
  { name: 'Educação', icon: Book },
  { name: 'Farmácia', icon: Pill },
  { name: 'Alimentação', icon: Utensils },
  { name: 'Combustível', icon: Fuel },
  { name: 'Transporte', icon: Car },
  { name: 'Pagamentos', icon: CreditCard },
  { name: 'Lazer e hobbies', icon: Gamepad2 },

  { name: 'Compras', icon: ShoppingBag },
  { name: 'Dívidas e Empréstimos', icon: FileSliders },
  { name: 'Viagem', icon: Plane },
  { name: 'Impostos e Taxas', icon: FileText },
  { name: 'Mercado', icon: ShoppingCart },

  { name: 'Saúde', icon: HeartPulse },
  { name: 'Higiene', icon: ShowerHead },
  { name: 'Vestuário', icon: Shirt },
  { name: 'Veículo', icon: Car },
  { name: 'Moradia', icon: Home },
  { name: 'Animais de Estimação', icon: PawPrint },
  { name: 'Outros', icon: ShoppingBag },
]
